name: quds_db
description: A sqflite expansion package that simplifies creating databases and tables, crud operations, queries with modelization
version: 0.0.5+7
homepage: https://www.alrazysoft.com
repository: https://github.com/MohammedAsaadAsaad/flutter_quds_db

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # flutter:
  #   sdk: flutter
  meta: ^1.7.0
  path: ^1.8.0
  path_provider: ^2.0.4
  sqflite_common: ^2.0.1+1
  sqlite3: ^1.2.0
  sqlite3_flutter_libs: ^0.5.0
  synchronized: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.1 
  # flutter_test:
    # sdk: flutter
 