name: quds_db
description: A sqflite expansion package that simplifies creating databases and tables, crud operations, queries with modelization
version: 0.0.4+3
homepage: https://www.alrazysoft.com
repository: https://github.com/MohammedAsaadAsaad/flutter_quds_db

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.4
  sqflite_common_ffi: ^2.0.0+3
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 